Repository tilt-dev/tilt, pull requests merged in 2021-06, with the labels that each got.

#4642 web: update LastClickedAt on UIButton click
  web/src/OverviewActionBar.tsx
  web/src/OverviewResourcePane.tsx
Labels: ui

#4649 engine: don't block tilt ci for local_resource with auto_init=False
  internal/engine/session/controller_test.go
  internal/engine/session/conv.go
Labels: bug

#4644 tiltfile: add working directory option to local and local_resource
  internal/engine/buildcontrol/local_target_build_and_deployer.go
  internal/tiltfile/docker.go
  internal/tiltfile/files.go
  internal/tiltfile/live_update.go
  internal/tiltfile/local_resource.go
  internal/tiltfile/telemetry/telemetry.go
  internal/tiltfile/tiltfile_test.go
  internal/tiltfile/value/value.go
Labels: enhancement

#4674 ci: add retry for Windows tests
  Makefile
Labels: Windows
