Repository tilt-dev/tilt, pull requests merged in 2021-07, with the labels that each got.

#4715 watch: upgrade fsnotify to fix spurious file changed on Windows
  go.mod
  go.sum
  vendor/github.com/tilt-dev/fsnotify/README.md
  vendor/github.com/tilt-dev/fsnotify/windows.go
  vendor/modules.txt
Labels: dependencies

#4724 web: Replace Grid with Table Overview
  web/.storybook/preview.js
  web/src/HUD.tsx
  web/src/OverviewGrid.stories.tsx
  web/src/OverviewGrid.test.tsx
  web/src/OverviewGrid.tsx
  web/src/OverviewItemView.stories.tsx
  web/src/OverviewItemView.test.tsx
  web/src/OverviewItemView.tsx
  web/src/OverviewPane.test.tsx
  web/src/OverviewPane.tsx
  web/src/OverviewTable.tsx
  web/src/OverviewTablePane.stories.tsx
  web/src/SidebarItemView.tsx
  web/src/SidebarTriggerModeToggle.test.tsx
  web/src/SidebarTriggerModeToggle.tsx
Labels: ui

#4723 web: add custom navbar button support
  web/public/index.html
  web/src/ApiButton.tsx
  web/src/CustomNav.tsx
  web/src/GlobalNav.tsx
  web/src/HeaderBar.tsx
  web/src/OverviewActionBar.tsx
  web/src/instrumentedComponents.tsx
  web/src/view.d.ts
Labels: ui

#4725 web: add SVG support for UIButton icons
  web/package.json
  web/src/ApiButton.tsx
  web/src/CustomNav.tsx
  web/yarn.lock
Labels: ui

#4786 tiltfile: add Tiltfile owner label to all manifests
  internal/engine/configs/api.go
  internal/testutils/manifestbuilder/manifestbuilder.go
  internal/tiltfile/tiltfile_state.go
  internal/tiltfile/tiltfile_test.go
Labels: bug

#4796 docker-compose: fix variable resolution type issues
  Makefile
  internal/dockercompose/client.go
  internal/dockercompose/client_test.go
Labels: bug

#4799 docker-compose: fix stack overflow panic
  internal/tiltfile/docker_compose.go
  internal/tiltfile/docker_compose_test.go
  internal/tiltfile/tiltfile_docker_compose_test.go
Labels: bug
